name: New source
description: Suggest a better SAT source
body:
  - type: input
    id: name
    attributes:
      label: Source name + URL
    validations:
      required: true
  - type: dropdown
    id: cost
    attributes:
      label: Cost
      options: [Free, Freemium, Paid]
  - type: textarea
    id: why
    attributes:
      label: Why beats Tier equivalent?
